name: Build manylinux1 wheels

on:
  push:
    branches: 
      - master
  create:

jobs:
  build_linux:
    using: 'docker'
    image: docker://quay.io/pypa/manylinux1_x86_64
    args:
        - .github/workflows/actions/entrypoint.sh
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: ./.github/workflows/actions/build-manylinux/
    - name: Upload Wheels
      uses: actions/upload-artifact@v1
      with: 
        name: manylinux1-wheels
        path: manylinux1-wheels
    - name: Publish to PyPI if tagged
      if: startsWith(github.ref, 'refs/tags')
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m pip install --upgrade pip
        pip install twine setuptools-scm
        python setup.py sdist
        twine upload manylinux1-wheels/fugashi*whl
        twine upload manylinux1-wheels/fugashi*.tar.gz

